#!/usr/bin/env node
/**
 * Validate the judge against episodes whose verdicts are already known.
 *
 * An eval is only worth its output if the grader itself is sound, so this runs
 * before any comparison is trusted. The fixtures are real captured outputs: a
 * clean episode the judge must not condemn, one that invents a show name and a
 * doctorate, and one produced from a silently truncated paper that discusses a
 * completely different subject. A judge that rates that last one as faithful is
 * broken, and this script fails loudly when it does.
 *
 *   npm run eval:validate
 */
import { runDeterministicChecks } from "../lib/eval/checks";
import { checkExpectation, loadFixtures, loadPaper, loadPapers } from "../lib/eval/dataset";
import { judgeEpisode } from "../lib/eval/judge";
import { getProvider } from "../lib/llm/index";
import { activeProvider, type ProviderName } from "../lib/config/env";
import { runEntry } from "./entry";

function pct(n: number): string {
  return `${(n * 100).toFixed(0)}%`;
}

/**
 * Re-judge one fixture several times to measure grader variance. Reported
 * because a difference between two models means nothing until it is larger
 * than the spread of the instrument measuring it.
 */
async function measureVariance(repeat: number) {
  const judgeName = (process.env.JUDGE_PROVIDER as ProviderName) ?? activeProvider();
  const provider = getProvider(judgeName);
  const papers = await loadPapers();
  const fixtures = await loadFixtures();

  console.log(`\n📏  Judge variance — ${repeat} runs per fixture (${provider.model})\n`);

  for (const fx of fixtures) {
    const pc = papers.find((p) => p.id === fx.paperId);
    if (!pc) continue;
    const paper = await loadPaper(pc);

    const scores: number[] = [];
    for (let i = 0; i < repeat; i++) {
      const j = await judgeEpisode(fx.episode, paper, pc.expectedContributions, {
        provider,
      });
      scores.push(j.faithfulness.faithfulness);
      process.stdout.write(`   ${fx.id} run ${i + 1}: ${pct(j.faithfulness.faithfulness)}\n`);
    }
    const mean = scores.reduce((a, b) => a + b, 0) / scores.length;
    const spread = Math.max(...scores) - Math.min(...scores);
    console.log(
      `   → ${fx.id}: mean ${pct(mean)}, spread ${(spread * 100).toFixed(1)} points\n`,
    );
  }
}

async function main() {
  const repeatArg = process.argv.indexOf("--repeat");
  if (repeatArg !== -1) {
    await measureVariance(Number(process.argv[repeatArg + 1] ?? 3));
    return;
  }

  const judgeName = (process.env.JUDGE_PROVIDER as ProviderName) ?? activeProvider();
  const provider = getProvider(judgeName);
  console.log(`\n⚖️   Judge: ${judgeName} / ${provider.model}\n`);

  const papers = await loadPapers();
  const fixtures = await loadFixtures();
  let failures = 0;

  for (const fx of fixtures) {
    const pc = papers.find((p) => p.id === fx.paperId);
    if (!pc) {
      console.log(`⏭️   ${fx.id}: paper "${fx.paperId}" not in sample_papers/, skipping.`);
      continue;
    }
    const paper = await loadPaper(pc);

    const deterministic = runDeterministicChecks({
      episode: fx.episode,
      paper,
      minutes: 4,
      showName: "PaperCast",
    });

    const judged = await judgeEpisode(
      fx.episode,
      paper,
      pc.expectedContributions,
      { provider },
    );
    const f = judged.faithfulness;

    const violations = checkExpectation(fx.expectation, {
      faithfulness: f.faithfulness,
      deterministicErrors: deterministic.errors,
    });
    if (violations.length) failures++;

    console.log(`${violations.length ? "❌" : "✅"} ${fx.id}`);
    console.log(`   generated by ${fx.generator.model}`);
    console.log(
      `   faithfulness ${pct(f.faithfulness)}  ·  hallucination ${pct(f.hallucinationRate)}  ·  coverage ${judged.coverage ? pct(judged.coverage.coverage) : "n/a"}`,
    );
    console.log(
      `   claims ${f.totalClaims} (${f.supported} supported, ${f.unsupported} unsupported, ${f.contradicted} contradicted)`,
    );
    console.log(
      `   deterministic ${pct(deterministic.complianceScore)} (${deterministic.errors} errors)`,
    );
    console.log(
      `   tokens ${judged.usage.inputTokens} in / ${judged.usage.outputTokens} out` +
        ` · cache ${judged.usage.cacheWriteTokens} write, ${judged.usage.cacheReadTokens} read` +
        ` · ${(judged.latencyMs / 1000).toFixed(1)}s`,
    );
    for (const v of violations) console.log(`   ⚠️  ${v}`);

    // Show a couple of failed claims to make the verdict inspectable.
    const bad = f.verdicts.filter((v) => v.verdict !== "supported").slice(0, 3);
    for (const b of bad) {
      console.log(`   · [${b.verdict}${b.specific ? ", specific" : ""}] ${b.claim.slice(0, 95)}`);
    }
    console.log();
  }

  if (failures) {
    console.error(`❌  Judge validation failed on ${failures} fixture(s). Do not trust eval numbers until this passes.\n`);
    process.exit(1);
  }
  console.log("✅  Judge validation passed. Every fixture landed inside its expected bounds.\n");
}

runEntry(main);
